### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by AVDeveloppement** [burma69/PM3UniversalGUI#2]
I use last proxmark3 of 04/01/2019 build
it seem i have problem because i use x64 version maybe?
When it start i have this message and form show but treeview are empty

> ---------------------------
> proxmark3.exe - Erreur système
> ---------------------------
> Impossible de démarrer le programme car il manque libwinpthread-1.dll sur votre ordinateur. Essayez de réinstaller le programme pour corriger ce problème. 
> ---------------------------
> OK   
---------------------------

Thanks for your work

**Comment by kieths** [comment]
I'm seeing the same problem.

OS: Windows 10 x64, version 10.0.17134 Build 17134
Windows Error: "The application has failed to start because its side-by-side configuration is incorrect.  Please see the application event log or use the command-line sxstrace.exe tool for more detail."

I attempted to run the sxstrace.exe utility (under Admin permissions), but the output log file appears non-useful (not human readable, other than file paths, filenames).

App version: Unknown (no file version shown under Properties/Details).

Ref URL (bin release dated 15/Sep/2018):
https://github.com/burma69/PM3UniversalGUI/tree/master/PM3UniversalGUI/bin/Release

Please let me know if I can provide further details / info.

**Comment by stephrsh** [comment]
Hi,

same problem here libwinpthread-1.dll,

Windows 7 x64 , latest official repo

**Comment by stephrsh** [comment]
ok finally get it worked 

I copied 4 files from ProxSpace-master\msys2\mingw32\bin to \client :
libwinpthread-1.dll 
libgcc_s_dw2-1.dll
libreadline6.dll
libtermcap-0.dll

Now it works

A path problem probably....

**Comment by AVDeveloppement** [comment]
hum you help me, i put it in ...msys2\mingw64\bin and modified path of proxmark in config files.
All work, thanks for your help.

**Comment by kieths** [comment]
Are you guys compiling from source?  Is there a compiled version available?

**Comment by kieths** [comment]
Hi Steph,

I've done so, and got a "side-by-side" error (I don't have a screen
capture here in the office).

And, for the latest official releases by Gator96100, the most recent
copies won't open (attached photo of the resulting blue box error, with
added reference builds and OS info).

Gator had an earlier build with the PM3GUI (version 1.1.1.0) that does run
ok, but it was not the latest, per Gator, so he included the newer build
(I assume 1.1.2.0).  With that version, it fails to run under Windows 10
x64 (version per photo).

I tried a feeble attempt to compile the source myself, but had no luck
under Windows (strangely, I find compiling under Linux easier than
Windows).

About the GUI - the concept is Great!  I don't (with v1.1.1.0) see the
same level of detail as in your examples (the right center panel does not
appear the same).  But in general, I find the reference very useful.

Best regards,
Kieth Swaney

On Thu, February 7, 2019 11:21 pm, stephrsh wrote:
| it's already an .EXE
|
https://github.com/burma69/PM3UniversalGUI/tree/master/PM3UniversalGUI/bin/Release
| just to put in the directory of pm
|
| --
| You are receiving this because you commented.
| Reply to this email directly or view it on GitHub:
| https://github.com/burma69/PM3UniversalGUI/issues/2#issuecomment-461713475

**Comment by kieths** [comment]
Hi Steph,

I just saw an update from Gator on the topic.

It appears the copy of your GUI utility was auto downloading in HTML
format based on Gator's script.  He believes he has that resolved now,
I'll test tonight.  I had previously tried downloading the files directly
myself, and placing them in the PM3 official build directory, but got the
previous side-by-side error (though properties did show v1.1.2.0 on the
EXE).  Perhaps it's just a matter of the download being decoded
incorrectly (possibly one of the files is being jumbled).

Will check results tonight.

Best regards,
Kieth Swaney



On Fri, February 8, 2019 11:52 am, Kieth Swaney wrote:
| Hi Steph,
|
| I've done so, and got a "side-by-side" error (I don't have a screen
| capture here in the office).
|
| And, for the latest official releases by Gator96100, the most recent
| copies won't open (attached photo of the resulting blue box error, with
| added reference builds and OS info).
|
| Gator had an earlier build with the PM3GUI (version 1.1.1.0) that does run
| ok, but it was not the latest, per Gator, so he included the newer build
| (I assume 1.1.2.0).  With that version, it fails to run under Windows 10
| x64 (version per photo).
|
| I tried a feeble attempt to compile the source myself, but had no luck
| under Windows (strangely, I find compiling under Linux easier than
| Windows).
|
| About the GUI - the concept is Great!  I don't (with v1.1.1.0) see the
| same level of detail as in your examples (the right center panel does not
| appear the same).  But in general, I find the reference very useful.
|
| Best regards,
| Kieth Swaney
|
| On Thu, February 7, 2019 11:21 pm, stephrsh wrote:
| | it's already an .EXE
| |
|
https://github.com/burma69/PM3UniversalGUI/tree/master/PM3UniversalGUI/bin/Release
| | just to put in the directory of pm
| |
| | --
| | You are receiving this because you commented.
| | Reply to this email directly or view it on GitHub:
| |
https://github.com/burma69/PM3UniversalGUI/issues/2#issuecomment-461713475
|

**Comment by kieths** [comment]
Hi Steph,

Gator has uploaded an updated official release version:
official-64-20190208-fbf77474f53809f57e8d32a8e6e210bf921c424b

File version is 1.1.2.0.

The GUI file opens and runs without immediate errors, but it appears to
still have an issue parsing target commands which had issue under v1.1.1.0
(the original reason why I was interested in the new build with v1.1.2.0).
 Specifically, I'm seeing problems specifically with "lf hid .." commands.
For example, "lf hid read", has not output of activity in the lower panel.
 The top right panel also appears to say it's unable to communicate with
the PM3, "Sending bytes to proxmark failed - offline". Regardless, it does
appear to be working, as the read command turns on the LED, and presumably
the PM3 begins to read / decode.

Also, the Exit and Quit commands appear to send the command to the PM3 app
to shutdown, but with somewhat unexpected results. If having run the above
"lf hid read" command and passed a card over the antenna several time,
then issuing the Quit command displays the "read" results, sometimes hangs
for several seconds while displaying the read results in the bottom right
panel, then eventually closes.

It is major progress, though.

Best regards,
Kieth Swaney


On Fri, February 8, 2019 12:02 pm, Kieth Swaney wrote:
| Hi Steph,
|
| I just saw an update from Gator on the topic.
|
| It appears the copy of your GUI utility was auto downloading in HTML
| format based on Gator's script.  He believes he has that resolved now,
| I'll test tonight.  I had previously tried downloading the files directly
| myself, and placing them in the PM3 official build directory, but got the
| previous side-by-side error (though properties did show v1.1.2.0 on the
| EXE).  Perhaps it's just a matter of the download being decoded
| incorrectly (possibly one of the files is being jumbled).
|
| Will check results tonight.
|
| Best regards,
| Kieth Swaney
|
|
|
| On Fri, February 8, 2019 11:52 am, Kieth Swaney wrote:
| | Hi Steph,
| |
| | I've done so, and got a "side-by-side" error (I don't have a screen
| | capture here in the office).
| |
| | And, for the latest official releases by Gator96100, the most recent
| | copies won't open (attached photo of the resulting blue box error, with
| | added reference builds and OS info).
| |
| | Gator had an earlier build with the PM3GUI (version 1.1.1.0) that does
run
| | ok, but it was not the latest, per Gator, so he included the newer build
| | (I assume 1.1.2.0).  With that version, it fails to run under Windows 10
| | x64 (version per photo).
| |
| | I tried a feeble attempt to compile the source myself, but had no luck
| | under Windows (strangely, I find compiling under Linux easier than
| | Windows).
| |
| | About the GUI - the concept is Great!  I don't (with v1.1.1.0) see the
| | same level of detail as in your examples (the right center panel does not
| | appear the same).  But in general, I find the reference very useful.
| |
| | Best regards,
| | Kieth Swaney
| |
| | On Thu, February 7, 2019 11:21 pm, stephrsh wrote:
| | | it's already an .EXE
| | |
| |
|
https://github.com/burma69/PM3UniversalGUI/tree/master/PM3UniversalGUI/bin/Release
| | | just to put in the directory of pm
| | |
| | | --
| | | You are receiving this because you commented.
| | | Reply to this email directly or view it on GitHub:
| | |
| https://github.com/burma69/PM3UniversalGUI/issues/2#issuecomment-461713475
| |
|
|
|
